name: action-brew-install
description: Install one or more tools using Homebrew

inputs:
  FORMULAS:
    description: A newline-delimited list of formulas to install
    required: true

runs:
  using: composite
  steps:
    -
      name: Set up Homebrew
      shell: bash
      run: |
        # Set up Homebrew
        
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        echo "$(brew --prefix)/bin" >> $GITHUB_PATH
    -
      name: Install formulas
      shell: bash
      env:
        FORMULAS: ${{ inputs.FORMULAS }}
        HOMEBREW_NO_AUTO_UPDATE: 1
      run: |
        # Install formulas
        while IFS= read -r FORMULA || [[ -n "$FORMULA" ]]; do
          if [[ -n "$FORMULA" ]]; then
            echo "::group::Installing $FORMULA"
            brew install "$FORMULA"
            echo "::endgroup::"
          fi
        done <<< "$FORMULAS"

branding:
  icon: arrow-down-circle
  color: 'blue'
